### ISSUE TITLE
Lack of UTF-8 encoding in generated reports

### ISSUE THREAD

**Issue by Sam0rai** [trustedsec/User-Behavior-Mapping-Tool#1]
When running your tool, I got the following error message:

> Traceback (most recent call last):
  File "D:\util\GitHub\Forensics\User-Behavior-Mapping-Tool\UserBehaviorAnalyzer.py", line 575, in <module>
    textfile.write(str(item) + "\n")
  File "C:\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-24: character maps to <undefined>

The error was fixed by changing line 575 to:
`textfile = open(outfolder+"Paths_Unique.txt", "w", encoding='utf-8')`

**Comment by api0cradle** [comment]
Thank you for that. Gonna check that further

**Comment by api0cradle** [comment]
Added the UTF-8 in this commit. Thank you
https://github.com/trustedsec/User-Behavior-Mapping-Tool/commit/abbcad8623292bfec32af000d4450cdfc584c4cb
